"""
FAISS vector store for the RAG pipeline.

Responsibilities:

- Store document embeddings.
- Associate embeddings with DocumentChunk objects.
- Perform semantic similarity search.
- Apply an optional similarity threshold.
- Persist the FAISS index and chunk metadata.

The embeddings generated by our embedding model are
normalized. Therefore, inner product similarity is
equivalent to cosine similarity.
"""

import json
import logging
from pathlib import Path

import faiss
import numpy as np

from src.models import DocumentChunk


logger = logging.getLogger(__name__)


class VectorStore:
    """
    Local FAISS vector store.

    FAISS stores the numerical vectors.

    Python stores the corresponding DocumentChunk objects
    so that retrieved vectors can be mapped back to their
    original document text and page metadata.
    """

    def __init__(self):
        """
        Create an empty vector store.
        """

        self.index = None

        # -------------------------------------------------
        # Store the embedding dimension.
        #
        # Example:
        #
        # all-MiniLM-L6-v2 produces 384-dimensional
        # embeddings.
        #
        # This is set when the first embeddings are added.
        # -------------------------------------------------

        self.dimension = None

        self.chunks: list[
            DocumentChunk
        ] = []


    def __len__(self) -> int:
        """
        Return the number of document chunks stored.

        This allows us to use:

            len(vector_store)

        which represents the number of indexed chunks.
        """

        return len(self.chunks)


    # =====================================================
    # ADD DOCUMENT CHUNKS
    # =====================================================

    def add(
        self,
        chunks: list[DocumentChunk],
        embeddings: list[list[float]],
    ) -> None:
        """
        Add document chunks and their embeddings.

        The number of chunks must match the number
        of embeddings.
        """

        if not isinstance(
            chunks,
            list,
        ):
            raise TypeError(
                "chunks must be a list."
            )

        if not isinstance(
            embeddings,
            list,
        ):
            raise TypeError(
                "embeddings must be a list."
            )

        if len(chunks) != len(embeddings):
            raise ValueError(
                "Number of chunks must match "
                "number of embeddings."
            )

        if not chunks:
            return

        # -------------------------------------------------
        # Convert embeddings to NumPy array.
        # -------------------------------------------------

        vectors = np.asarray(
            embeddings,
            dtype="float32",
        )

        if vectors.ndim != 2:
            raise ValueError(
                "Embeddings must be a 2D array."
            )

        # -------------------------------------------------
        # Create the FAISS index on first insertion.
        #
        # IndexFlatIP:
        #
        # IP = Inner Product
        #
        # Because our embeddings are normalized,
        # this gives cosine similarity.
        # -------------------------------------------------

        if self.index is None:

            dimension = vectors.shape[1]

            self.index = faiss.IndexFlatIP(
                dimension
            )

            # Store the embedding dimension so that
            # callers can inspect the vector store
            # without accessing the FAISS object directly.

            self.dimension = dimension

            logger.info(
                "Created FAISS index with dimension %d.",
                dimension,
            )

        # -------------------------------------------------
        # Validate embedding dimensions.
        # -------------------------------------------------

        if vectors.shape[1] != self.index.d:

            raise ValueError(
                "Embedding dimension does not match "
                "the existing FAISS index."
            )

        # -------------------------------------------------
        # Add vectors to FAISS.
        # -------------------------------------------------

        self.index.add(
            vectors
        )

        # -------------------------------------------------
        # Store corresponding chunks.
        #
        # FAISS position 0 corresponds to chunks[0].
        # FAISS position 1 corresponds to chunks[1].
        # etc.
        # -------------------------------------------------

        self.chunks.extend(
            chunks
        )

        logger.info(
            "Added %d chunks to vector store.",
            len(chunks),
        )


    # =====================================================
    # SEARCH
    # =====================================================

    def search(
        self,
        query_embedding: list[float],
        top_k: int = 5,
        score_threshold: float | None = None,
    ) -> list[
        tuple[DocumentChunk, float]
    ]:
        """
        Search the vector store for semantically similar chunks.

        Parameters
        ----------
        query_embedding:
            Embedding vector for the user's question.

        top_k:
            Maximum number of results to return.

        score_threshold:
            Optional minimum similarity score.

            Example:

                score_threshold=0.25

            means results below 0.25 are discarded.

        Returns
        -------
        list of:
            (DocumentChunk, similarity_score)
        """

        # -------------------------------------------------
        # An empty vector store cannot perform a search.
        #
        # Raising RuntimeError makes this failure explicit
        # instead of silently returning an empty result.
        # -------------------------------------------------

        if self.index is None or not self.chunks:

            raise RuntimeError(
                "Cannot search an empty vector store."
            )

        if not isinstance(
            query_embedding,
            list,
        ):

            raise TypeError(
                "query_embedding must be a list."
            )

        if top_k <= 0:

            raise ValueError(
                "top_k must be greater than zero."
            )

        # -------------------------------------------------
        # Do not ask FAISS for more vectors than exist.
        # -------------------------------------------------

        search_k = min(
            top_k,
            len(self.chunks),
        )

        # -------------------------------------------------
        # Convert query into NumPy format.
        # -------------------------------------------------

        query_vector = np.asarray(
            [query_embedding],
            dtype="float32",
        )

        if query_vector.ndim != 2:

            raise ValueError(
                "Query embedding must be a 1D vector."
            )

        if query_vector.shape[1] != self.index.d:

            raise ValueError(
                "Query embedding dimension does not "
                "match the FAISS index."
            )

        # -------------------------------------------------
        # Search FAISS.
        # -------------------------------------------------

        scores, indices = (
            self.index.search(
                query_vector,
                search_k,
            )
        )

        results = []

        # -------------------------------------------------
        # Convert FAISS results back to DocumentChunks.
        # -------------------------------------------------

        for score, index in zip(
            scores[0],
            indices[0],
        ):

            # FAISS uses -1 when no result exists.

            if index < 0:
                continue

            similarity_score = float(
                score
            )

            # -------------------------------------------------
            # Apply optional threshold.
            # -------------------------------------------------

            if (
                score_threshold is not None
                and similarity_score < score_threshold
            ):
                continue

            chunk = self.chunks[
                index
            ]

            results.append(
                (
                    chunk,
                    similarity_score,
                )
            )

        logger.info(
            "Vector search returned %d results.",
            len(results),
        )

        return results


    # =====================================================
    # SAVE
    # =====================================================

    def save(
        self,
        directory: str | Path,
    ) -> None:
        """
        Save the FAISS index and chunk metadata to disk.

        Files created:

            index.faiss
            chunks.json
        """

        if self.index is None:

            raise ValueError(
                "Cannot save an empty vector store."
            )

        directory = Path(
            directory
        )

        directory.mkdir(
            parents=True,
            exist_ok=True,
        )

        index_path = (
            directory / "index.faiss"
        )

        chunks_path = (
            directory / "chunks.json"
        )

        # -------------------------------------------------
        # Save FAISS index.
        # -------------------------------------------------

        faiss.write_index(
            self.index,
            str(index_path),
        )

        # -------------------------------------------------
        # Save chunk metadata.
        # -------------------------------------------------

        chunks_data = [
            chunk.model_dump()
            for chunk in self.chunks
        ]

        with open(
            chunks_path,
            "w",
            encoding="utf-8",
        ) as file:

            json.dump(
                chunks_data,
                file,
                indent=2,
                ensure_ascii=False,
            )

        logger.info(
            "Vector store saved to %s.",
            directory,
        )


    # =====================================================
    # LOAD
    # =====================================================

    @classmethod
    def load(
        cls,
        directory: str | Path,
    ) -> "VectorStore":
        """
        Load a previously saved vector store.
        """

        directory = Path(
            directory
        )

        index_path = (
            directory / "index.faiss"
        )

        chunks_path = (
            directory / "chunks.json"
        )

        if not index_path.exists():

            raise FileNotFoundError(
                f"FAISS index not found: {index_path}"
            )

        if not chunks_path.exists():

            raise FileNotFoundError(
                f"Chunk metadata not found: {chunks_path}"
            )

        store = cls()

        # -------------------------------------------------
        # Load FAISS index.
        # -------------------------------------------------

        store.index = faiss.read_index(
            str(index_path)
        )

        # -------------------------------------------------
        # Restore the embedding dimension.
        #
        # FAISS stores the dimension internally as `d`.
        # -------------------------------------------------

        store.dimension = store.index.d

        # -------------------------------------------------
        # Load chunk metadata.
        # -------------------------------------------------

        with open(
            chunks_path,
            "r",
            encoding="utf-8",
        ) as file:

            chunks_data = json.load(
                file
            )

        store.chunks = [
            DocumentChunk.model_validate(
                item
            )
            for item in chunks_data
        ]

        # -------------------------------------------------
        # Verify that FAISS and the chunk metadata are
        # still aligned.
        # -------------------------------------------------

        if (
            store.index.ntotal
            != len(store.chunks)
        ):

            raise ValueError(
                "FAISS index and chunk metadata "
                "contain different numbers of items."
            )

        logger.info(
            "Loaded vector store containing %d chunks.",
            len(store.chunks),
        )

        return store